#pragma once

#include "generated/latin_fonts.h"
#include "generated/hebrew_fonts.h"
#include "generated/jp_fonts.h"
#include "generated/kr_fonts.h"
#include "generated/arabic_fonts.h"
#include "generated/devanagari_fonts.h"
#include "generated/bengali_fonts.h"
#include "generated/telugu_fonts.h"
#include "generated/tamil_fonts.h"
#include "generated/thai_fonts.h"
#include "generated/georgian_fonts.h"
#include "generated/armenian_fonts.h"
#include "generated/bopomofo_fonts.h"
#include "generated/vietnamese_fonts.h"
#include "generated/symbol_fonts.h"
#include "generated/emoji_fonts.h"

#include "gfx_icons.h"
#include "FreeSansBold24pt7b.h"

const GFXfont* const ALL_FONTS [] = {
  &IconsFont,
  &NotoSans_Regular_Base_14pt7b,
  &NotoColorEmoji_Regular_ToolsBMP_20pt16b,
  &NotoColorEmoji_Regular_EmjHandsBMP2_20pt16b,
  &NotoSansSymbols2_Regular_SymBmp1_20pt16b,
  &NotoSansSymbols2_Regular_SymBmp2_20pt16b,
  &NotoSansSymbols2_Regular_SymBmp3_20pt16b,
  &NotoSansSymbols2_Regular_SymBmp4_20pt16b,
  &NotoSansSymbols2_Regular_SymBmp5_20pt16b,
  &NotoSansSymbols2_Regular_SymBmp6_20pt16b,
  &NotoColorEmoji_Regular_Zodiac_20pt16b,
  &NotoSans_Regular_LatinExtB_14pt16b,
  &NotoSans_Regular_Schwa_14pt16b,
  &NotoSans_Regular_SupAndExtA_14pt16b,
  &NotoColorEmoji_Regular_EmjTravelBMP_20pt16b,
  &NotoSans_Regular_CurrencySigns_14pt16b,
  &NotoColorEmoji_Regular_Hyper_18pt16b,
  &NotoColorEmoji_Regular_Meh_20pt16b,
  &NotoColorEmoji_Regular_Settings_20pt16b,
  &NotoColorEmoji_Regular_World_20pt16b,
  &NotoSansSymbols2_Regular_Arrows_20pt16b,
  &NotoSansSymbols2_Regular_Technical2_20pt16b,
  &NotoSansSymbols_Regular_Technical_20pt16b,
  &NotoColorEmoji_Regular_ClipCpy_18pt16b,
  &NotoColorEmoji_Regular_FileOpen_14pt16b,
  &NotoSansSymbols2_Regular_Util_20pt16b,
  &NotoColorEmoji_Regular_Brightness_16pt16b,
  &NotoColorEmoji_Regular_Find_18pt16b,
  &NotoColorEmoji_Regular_Lock_18pt16b,
  &NotoColorEmoji_Regular_Note_12pt16b,
  &NotoSansSymbols2_Regular_Window_18pt16b,
  &NotoColorEmoji_Regular_AI_20pt16b,
  &NotoColorEmoji_Regular_Emojis0_20pt16b,
  &NotoColorEmoji_Regular_Light_20pt16b,
  &NotoColorEmoji_Regular_Emojis2_20pt16b,
  &NotoSansJP_Regular_Cjk4e2d_15pt16b,
  &NotoSansJP_Regular_Cjk5eff_15pt16b,
  &NotoSansJP_Regular_Cjk96e3_15pt16b,
  &NotoSansJP_Regular_Cjk91cd_15pt16b,
  &NotoSansJP_Regular_KangXi_15pt16b,
  &NotoColorEmoji_Regular_EmjAnimals2_20pt16b,
  &NotoColorEmoji_Regular_EmjAnimals3_20pt16b,
  &NotoColorEmoji_Regular_EmjAnimals4_20pt16b,
  &NotoColorEmoji_Regular_EmjAnimals5_20pt16b,
  &NotoColorEmoji_Regular_EmjAnimals_20pt16b,
  &NotoColorEmoji_Regular_EmjBody2_20pt16b,
  &NotoColorEmoji_Regular_EmjBuildings_20pt16b,
  &NotoColorEmoji_Regular_EmjCelebrate_20pt16b,
  &NotoColorEmoji_Regular_EmjClocks_20pt16b,
  &NotoColorEmoji_Regular_EmjClothing2_20pt16b,
  &NotoColorEmoji_Regular_EmjClothing_20pt16b,
  &NotoColorEmoji_Regular_EmjEffects_20pt16b,
  &NotoColorEmoji_Regular_EmjFaces2_20pt16b,
  &NotoColorEmoji_Regular_EmjFaces3_20pt16b,
  &NotoColorEmoji_Regular_EmjFaces_20pt16b,
  &NotoColorEmoji_Regular_EmjFantasy_20pt16b,
  &NotoColorEmoji_Regular_EmjFood2_20pt16b,
  &NotoColorEmoji_Regular_EmjFood3_20pt16b,
  &NotoColorEmoji_Regular_EmjFood4_20pt16b,
  &NotoColorEmoji_Regular_EmjFood5_20pt16b,
  &NotoColorEmoji_Regular_EmjFood_20pt16b,
  &NotoColorEmoji_Regular_EmjGestures_20pt16b,
  &NotoColorEmoji_Regular_EmjHands2_20pt16b,
  &NotoColorEmoji_Regular_EmjHands3_20pt16b,
  &NotoColorEmoji_Regular_EmjHearts_20pt16b,
  &NotoColorEmoji_Regular_EmjHousehold_20pt16b,
  &NotoColorEmoji_Regular_EmjInsects_20pt16b,
  &NotoColorEmoji_Regular_EmjLove_20pt16b,
  &NotoColorEmoji_Regular_EmjObjects1_20pt16b,
  &NotoColorEmoji_Regular_EmjObjects2_20pt16b,
  &NotoColorEmoji_Regular_EmjParts_20pt16b,
  &NotoColorEmoji_Regular_EmjPeople2_20pt16b,
  &NotoColorEmoji_Regular_EmjPeople3_20pt16b,
  &NotoColorEmoji_Regular_EmjPeople4_20pt16b,
  &NotoColorEmoji_Regular_EmjPeople_20pt16b,
  &NotoColorEmoji_Regular_EmjPlants_20pt16b,
  &NotoColorEmoji_Regular_EmjRaised_20pt16b,
  &NotoColorEmoji_Regular_EmjSciTools_20pt16b,
  &NotoColorEmoji_Regular_EmjSmileys2_20pt16b,
  &NotoColorEmoji_Regular_EmjSports2_20pt16b,
  &NotoColorEmoji_Regular_EmjSports3_20pt16b,
  &NotoColorEmoji_Regular_EmjSports_20pt16b,
  &NotoColorEmoji_Regular_EmjToys_20pt16b,
  &NotoColorEmoji_Regular_EmjTravelExt_20pt16b,
  &NotoColorEmoji_Regular_EmjTravel_20pt16b,
  &NotoColorEmoji_Regular_EmjWeatherSMP1_20pt16b,
  &NotoColorEmoji_Regular_EmjWeatherSMP2_20pt16b,
  &NotoColorEmoji_Regular_EmjTravelBMP2_20pt16b,
  &NotoColorEmoji_Regular_Emojis1_20pt16b,
  &NotoSansArabic_Regular_FormsB_16pt16b,
  &NotoSansArabic_Regular_Isolated_16pt16b,
  &NotoSansArabic_Regular_PerArab_16pt16b,
  &NotoSansDevanagari_Regular_Deva_16pt16b,
  &NotoSansDevanagari_Regular_DevaMatra_16pt7b,
  &NotoSansBengali_Regular_Bengali_16pt16b,
  &NotoSansBengali_Regular_BengaliMatra_16pt7b,
  &NotoSansTelugu_Regular_Telugu_16pt16b,
  &NotoSansTelugu_Regular_TeluguMatra_16pt7b,
  &NotoSansTamil_Regular_Tamil_14pt16b,
  &NotoSansTamil_Regular_TamilMatra_14pt7b,
  &NotoSansThai_Regular_Thai_16pt16b,
  &NotoSansThai_Regular_ThaiMatra_16pt7b,
  &NotoSansGeorgian_Regular_Georgian_17pt16b,
  &NotoSansArmenian_Regular_Armenian_16pt16b,
  &NotoSansTC_Regular_Bopomofo_16pt16b,
  &NotoSans_Regular_VietTones_16pt7b,
  &NotoSansJP_Regular_Hiragana_15pt16b,
  &NotoSansJP_Regular_Punct2_15pt16b,
  &NotoSansJP_Regular_Punct_15pt16b,
  &NotoSansHebrew_Medium_HebrewDots_22pt16b,
  &NotoSansHebrew_Medium_Hebrew_16pt16b,
  &NotoSans_Regular_Cyrillic_16pt16b,
  &NotoSans_Regular_Greek_14pt16b,
  &NotoSans_Regular_LetterMod_14pt16b,
  &NotoSans_Regular_SZ_14pt16b,
  &NotoSerifKR_Medium_Consonants_21pt16b,
  &NotoSerifKR_Medium_Vowels_21pt16b,
};

#define ALL_FONT_SIZE (sizeof(ALL_FONTS) / sizeof(GFXfont*))
