// Copyright 2026 thpoll83
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Known-answer tests for the vendored Monocypher build — the Ed25519 check that
// gates firmware signing (FW-2) and the SHA-512 it is built on. The point is not
// to test Monocypher (upstream does that); it is to pin THIS tree's build of it:
// a toolchain flag, a bad merge of the vendored files, or an accidental edit that
// breaks the crypto should fail here on the host, not as a keyboard that refuses
// (or worse, accepts) every image in the field.
//
// Vectors are RFC 8032 §7.1 (TEST 1–3) and the FIPS 180-2 "abc" SHA-512 vector —
// authoritative published values, not generated by this code.

#include "gtest/gtest.h"

extern "C" {
#include "monocypher-ed25519.h"
}

#include <cstring>

namespace {

// Hex helper — the vectors below are transcribed straight from the RFCs.
static void from_hex(const char *hex, uint8_t *out, size_t out_len) {
    for (size_t i = 0; i < out_len; i++) {
        unsigned v = 0;
        sscanf(hex + 2 * i, "%2x", &v);
        out[i] = (uint8_t)v;
    }
}

// RFC 8032 §7.1 TEST 3: a 2-byte message, the shape closest to real use
// (non-empty message, standalone public key).
const char *kTest3Pub = "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025";
const char *kTest3Msg = "af82";
const char *kTest3Sig = "6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5ac3ac"
                        "18ff9b538d16f290ae67f760984dc6594a7c15e9716ed28dc027beceea1ec40a";

// RFC 8032 §7.1 TEST 1: the empty message — the degenerate length the length
// arithmetic gets wrong first.
const char *kTest1Pub = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a";
const char *kTest1Sig = "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e06522490155"
                        "5fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b";

class Ed25519KnownAnswerTest : public ::testing::Test {
   protected:
    uint8_t pub_[32];
    uint8_t sig_[64];
    uint8_t msg_[2];

    void SetUp() override {
        from_hex(kTest3Pub, pub_, sizeof pub_);
        from_hex(kTest3Sig, sig_, sizeof sig_);
        from_hex(kTest3Msg, msg_, sizeof msg_);
    }
};

TEST_F(Ed25519KnownAnswerTest, Rfc8032Test3SignatureVerifies) {
    EXPECT_EQ(0, crypto_ed25519_check(sig_, pub_, msg_, sizeof msg_));
}

TEST_F(Ed25519KnownAnswerTest, Rfc8032Test1EmptyMessageVerifies) {
    uint8_t pub[32], sig[64];
    from_hex(kTest1Pub, pub, sizeof pub);
    from_hex(kTest1Sig, sig, sizeof sig);
    EXPECT_EQ(0, crypto_ed25519_check(sig, pub, nullptr, 0));
}

TEST_F(Ed25519KnownAnswerTest, AFlippedMessageBitIsRejected) {
    msg_[0] ^= 0x01;
    EXPECT_EQ(-1, crypto_ed25519_check(sig_, pub_, msg_, sizeof msg_));
}

TEST_F(Ed25519KnownAnswerTest, AFlippedSignatureBitIsRejected) {
    sig_[63] ^= 0x80;
    EXPECT_EQ(-1, crypto_ed25519_check(sig_, pub_, msg_, sizeof msg_));
}

TEST_F(Ed25519KnownAnswerTest, TheWrongPublicKeyIsRejected) {
    uint8_t other[32];
    from_hex(kTest1Pub, other, sizeof other);
    EXPECT_EQ(-1, crypto_ed25519_check(sig_, other, msg_, sizeof msg_));
}

TEST_F(Ed25519KnownAnswerTest, SignRoundTripsThroughCheck) {
    // The keyboard only ever checks, but sign+check in one process pins the two
    // halves of the vendored code against each other as well as the vectors.
    uint8_t seed[32] = {0};
    uint8_t sk[64], pk[32], sig[64];
    crypto_ed25519_key_pair(sk, pk, seed);
    const uint8_t msg[] = {'p', 'o', 'l', 'y'};
    crypto_ed25519_sign(sig, sk, msg, sizeof msg);
    EXPECT_EQ(0, crypto_ed25519_check(sig, pk, msg, sizeof msg));
    sig[0] ^= 1;
    EXPECT_EQ(-1, crypto_ed25519_check(sig, pk, msg, sizeof msg));
}

TEST(Sha512KnownAnswerTest, Fips180AbcVector) {
    const char *expect_hex = "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a"
                             "2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f";
    uint8_t     expect[64], got[64];
    from_hex(expect_hex, expect, sizeof expect);
    const uint8_t msg[] = {'a', 'b', 'c'};
    crypto_sha512(got, msg, sizeof msg);
    EXPECT_EQ(0, memcmp(expect, got, sizeof got));
}

} // namespace
