// Font structures for newer Adafruit_GFX (1.1 and later).
// Example fonts are included in 'Fonts' directory.
// To use a font in your Arduino sketch, #include the corresponding .h
// file and pass address of GFXfont struct to setFont().  Pass NULL to
// revert to 'classic' fixed-space bitmap font.

#ifndef _GFXFONT_H_
#define _GFXFONT_H_

#include <stdint.h>

/// Font data stored PER GLYPH
typedef struct {
  uint16_t bitmapOffset; ///< Pointer into GFXfont->bitmap
  int8_t width;         ///< Bitmap dimensions in pixels
  int8_t height;        ///< Bitmap dimensions in pixels
  int8_t xAdvance;      ///< Distance to advance cursor (x axis)
  int8_t xOffset;        ///< X dist from cursor pos to UL corner
  int8_t yOffset;        ///< Y dist from cursor pos to UL corner
} GFXglyph;

/// Data stored for FONT AS A WHOLE
typedef struct {
  uint8_t *bitmap;  ///< Glyph bitmaps, concatenated
  GFXglyph *glyph;  ///< Glyph array
  uint32_t first;   ///< Unicode codepoint extents (first char) — 32-bit so SMP
                    ///< codepoints (> 0xFFFF, e.g. emoji at 0x1F600) are stored
                    ///< directly, with no Private-Use-Area shift
  uint32_t last;    ///< Unicode codepoint extents (last char)
  int8_t yAdvance; ///< Newline distance (y axis)
} GFXfont;

/// Column-native (OLED page-format) companion for ONE range GFXfont.
///
/// The keycap OLED buffer is column-major (one byte = 8 vertical pixels) while
/// GFXfont bitmaps are row-major (one byte = 8 horizontal pixels). Drawing a
/// legend glyph therefore normally walks pixel-by-pixel. This companion holds
/// every glyph of `font` pre-transposed into the buffer's own column-major
/// layout, so the draw becomes a whole-byte vertical blit straight from flash —
/// no boot-time transpose, no RAM cache. `bitmaps` is the concatenated
/// column-major store; `offsets[gi]` is the byte offset of font-local glyph gi
/// (columns run x=0..width-1, each ceil(height/8) page-bytes). Generated by
/// `fonts/gen_colfont.py`; consumed by kdisp_set_base_colfont() in disp_array.c.
typedef struct {
  const GFXfont  *font;    ///< The row-major font this mirrors (metrics + identity)
  const uint8_t  *bitmaps; ///< Column-major glyph bytes, concatenated
  const uint16_t *offsets; ///< Per-glyph byte offset into `bitmaps` (font-local index)
} GFXfontCol;

#endif // _GFXFONT_H_
