#!/usr/bin/env bash
# Generate the three standalone UI text fonts — the ones that render the status
# OLED, the firmware-update screens and the language-code labels:
#
#   base/fonts/NotoSans_Medium_Base_8pt.h     _Small_ 15 px  status OLED body rows
#   base/fonts/util_font.h                    _Mid_   19 px  status OLED TOP row,
#                                                            fw-update / utility text
#   base/fonts/nano_font.h                    _Nano_  10 px  language codes +
#                                                            split42 layout name
#
# These are NOT in fonts.yaml / ALL_FONTS — each is used through a dedicated
# single-font array (see split72/status_oled.c, split42/status_oled.c,
# oled_helper.c, poly_keymap.c), so they never compete with _Base_ over ASCII.
# The _Small_ Base header previously had no generator at all -- it was hand-made
# from a long-gone local NotoSans-Medium.ttf; this script is now the single source
# of truth for all three.  There used to be a separate 21 px _Disp_ face for the
# status-OLED top row; at that size grid-fitting has essentially converged with
# the unhinted render, so it bought nothing over _Mid_ 19 px and was dropped.
#
# ── Why these particular flags ───────────────────────────────────────────────
#
# -Hauto  Force FreeType's autohinter.  These sizes are 11-21 px em, where a stem
#         is 1-2 px, so whether the outline is snapped to the pixel grid decides
#         whether the two edges of one stem round the same way.  Unhinted, they
#         round independently: the same stem lands 1 px on one side of a glyph
#         and 2 px on the other, round bowls go lopsided and crossbars drop out.
#         That is exactly what the digits used to look like.
#         NotoSans ships as a VARIABLE font with NO hinting bytecode at all
#         (maxSizeOfInstructions == 0, no fpgm, a 7-byte prep that only sets
#         dropout control), and FreeType does NOT fall back to its own autohinter
#         when a face has even that stub prep — so without -Hauto these render
#         completely ungridfitted.  fontconvert's TT_INTERPRETER_VERSION_35 does
#         not help either: there is no bytecode for it to interpret.
#
# -pN     Em size in PIXELS.  -s is points at a fixed 141 DPI, so it can only
#         reach even ppem (-s6 -> 12, -s7 -> 14, -s8 -> 16 ...).  Grid-fitting
#         snaps cap-height to whole pixels, so the reachable heights jump in
#         steps; the size that keeps each font's on-screen footprint while gaining
#         grid-fitting simply is not expressible in points.  Every size here was
#         picked by measuring cap-height / x-height and the worst-case string
#         widths against the previous header, so the status-OLED layout does not
#         move (see keyboards/polykybd/.claude/skills/status-oled-layout).
#
# -wN     Weight on the variable font's wght axis.  Grid-fitting at a fixed size
#         can thin strokes out; the weight is what puts the mass back.
#
# Requirements:
#   * NotoSans at fonts/noto-sans/NotoSans-Regular.ttf (fetched by fonts/dl-fonts.sh)
#   * a fontconvert with -H and -p support — see AdafruitGFX.  For byte-reproducible
#     output use the PINNED build (FreeType 2.13.3 / HarfBuzz 2.6.7); the distro
#     fast-path build differs by ~1px on a few glyphs.  Override with $FONTCONVERT.
set -euo pipefail
cd "$(dirname "$0")/.."                       # -> the keyboard directory

FONTCONVERT="${FONTCONVERT:-fontconvert}"
SANS="fonts/noto-sans/NotoSans-Regular.ttf"

if [ ! -f "$SANS" ]; then
    echo "ERROR: $SANS missing — run fonts/dl-fonts.sh first" >&2
    exit 1
fi

# emit <out> <description> <fontconvert args...>
emit() {
    local out="$1"; shift
    local desc="$1"; shift
    {
        echo "// Copyright 2025 thpoll83"
        echo "// SPDX-License-Identifier: GPL-2.0-or-later"
        echo "#pragma once"
        echo "// GENERATED by fonts/gen-status-fonts.sh — do not hand-edit."
        echo "// $desc"
        "$FONTCONVERT" -f"$SANS" "$@" 0x20 0x7e
    } > "$out"
    echo "wrote $out"
}

emit base/fonts/NotoSans_Medium_Base_8pt.h \
     "Status-OLED body font (NotoSans Semibold 15 px, grid-fitted) — the rows that carry the numbers." \
     -p15 -w600 -Hauto -v_Small_

emit base/fonts/util_font.h \
     "Mid utility-label font (NotoSans Medium 19 px, grid-fitted) — status-OLED top row, fw-update screens, misc utility-key text." \
     -p19 -w500 -Hauto -v_Mid_

# split42's layout name has only the 32 px portrait width for a 5-char name. It
# used to be _Mid_ drawn through a 2x2-OR half-scale downsample, which is exactly
# the wrong thing for grid-fitted output: ORing pairs of pixels together thickens
# every stem back to ~2 px and closes the counters the grid-fitting just opened
# ("Qwrty" ran its w and r together). Render at the real size instead. 10 px is
# the largest that still fits the column -- the widest short name, "Wkmn", is
# 30 px here and 33 px at the _Tiny_ 11 px size, i.e. 1 px past the panel.
emit base/fonts/nano_font.h \
     "Nano label font (NotoSans Medium 10 px, grid-fitted) — language codes + the split42 layout name." \
     -p10 -w500 -Hauto -v_Nano_
