#!/usr/bin/env bash
# Generate the two standalone font headers used by the language-selection layer
# (_LL):
#
#   base/fonts/flag_fonts.h        country flags (NotoColorEmoji, 28 px)
#   (the tiny language-code label font moved to fonts/gen-status-fonts.sh)
#
# Both are used via dedicated single-font arrays in the keymap (see
# render_lang_flag_key in split72/keymaps/default/keymap.c); they are NOT part of
# fonts.yaml / ALL_FONTS — like the status-OLED fonts they are standalone
# committed headers.  Re-run this only when the language list or the look changes.
#
# Each flag is a two-codepoint regional-indicator pair (e.g. US = U+1F1FA U+1F1F8)
# shaped by HarfBuzz into a single glyph, then mapped to a Private-Use codepoint
# (FLAG_CP_BASE + LANG_* enum index) via fontconvert's -F option, so the firmware
# can address it as one char.
#
# Requirements:
#   * NotoColorEmoji   at fonts/Noto_CEmoji/NotoColorEmoji-Regular.ttf
#   * NotoSans         at fonts/noto-sans/NotoSans-Regular.ttf
#       (both fetched by fonts/dl-fonts.sh)
#   * a fontconvert with -F (sequence base codepoint) support — see AdafruitGFX.
#     For byte-reproducible output use the PINNED build (FreeType 2.13.3 /
#     HarfBuzz 2.6.7); the distro fast-path build differs by ~1px on a few glyphs.
#     Override the binary with $FONTCONVERT.
#
# IMPORTANT: the country list below MUST stay in the same order as
# enum lang_layer in lang/lang_lut.h (LANG_ENUS = 0, LANG_DEDE = 1, ...), so that
# flag codepoint == FLAG_CP_BASE + LANG_* and local_state->lang indexes it.
set -euo pipefail
cd "$(dirname "$0")/.."                       # -> the keyboard directory

FONTCONVERT="${FONTCONVERT:-fontconvert}"
EMOJI="fonts/Noto_CEmoji/NotoColorEmoji-Regular.ttf"
SANS="fonts/noto-sans/NotoSans-Regular.ttf"
FLAG_OUT="base/fonts/flag_fonts.h"
FLAG_BASE="0xE000"                            # keep in sync with FLAG_CP_BASE in the keymap

# ISO 3166-1 alpha-2 country code per language, in enum lang_layer order.
# DERIVED from the single source of truth, lang/lang_lut.xlsx: the "YY" part of
# each "xx-YY" language name in key_lut row 1, in column (= enum) order. Never
# hand-edit this list - add the language to the spreadsheet and re-run.
# Capture the extractor's stdout AND exit status first, so a partial dump
# followed by a Python error fails the whole script instead of silently
# truncating COUNTRIES (which would shift every LANG_* flag off its enum index).
countries="$("${PYTHON:-python3}" - lang/lang_lut.xlsx <<'PY'
import sys
from openpyxl import load_workbook
sheet = load_workbook(sys.argv[1], read_only=True, data_only=True)["key_lut"]
i = 0
while True:
    name = sheet.cell(row=1, column=2 + i * 4).value
    if not name:
        break
    print(name.split("-")[1].upper())   # es-MX -> MX, th-TH -> TH, ...
    i += 1
PY
)" || {
    echo "ERROR: could not read the language list from lang/lang_lut.xlsx" \
         "(need ${PYTHON:-python3} with openpyxl)." >&2
    exit 1
}
if [ -z "$countries" ]; then
    echo "ERROR: empty language list from lang/lang_lut.xlsx" \
         "(need ${PYTHON:-python3} with openpyxl)." >&2
    exit 1
fi
mapfile -t COUNTRIES <<<"$countries"

# Regional-indicator codepoint (hex) for an ASCII A-Z letter.
ri() { printf '%X' "$(( 0x1F1E6 + $(printf '%d' "'$1") - 65 ))"; }

seq=""
for cc in "${COUNTRIES[@]}"; do
    pair="$(ri "${cc:0:1}") $(ri "${cc:1:1}")"
    seq="${seq:+$seq, }$pair"
done

# ── flags ────────────────────────────────────────────────────────────────────
{
    echo "// Copyright 2025 thpoll83"
    echo "// SPDX-License-Identifier: GPL-2.0-or-later"
    echo "#pragma once"
    echo "// GENERATED by fonts/gen-lang-fonts.sh — do not hand-edit."
    echo "// Language-layer country flags: NotoColorEmoji, rendered at 54 px (taller"
    echo "// than the 40 px keycap) so the keymap can vertically centre + clip them and"
    echo "// have the flag content fill the height.  1 px inner border, Floyd-Steinberg"
    echo "// dither.  first = ${FLAG_BASE} + LANG_* enum index"
    echo "// (order = enum lang_layer in lang/lang_lut.h)."
    "$FONTCONVERT" -f"$EMOJI" -s20 -g -r54 -W72 -O1 -Dfs -e-0.10 \
                   -F"$FLAG_BASE" -v_LangFlags_ -S "$seq"
} > "$FLAG_OUT"
echo "wrote $FLAG_OUT ($(grep -c '// seq\[' "$FLAG_OUT") flags)"

# Flag render-settings sidecar for the host font-pack editor: the flag font is
# NOT in fonts.yaml, so generate_fonts.py emits no render record for it.  Without
# this the host can't rebuild a flag (sequence mode + the per-flag regional-
# indicator pair).  Mirrors the fontconvert flags above + the seq.  ⚠ Mirrored
# byte-identically in PolyKybdHost/polyhost/res/fontpack/lang_flags.json (cmp).
FLAGS_JSON="base/fonts/generated/lang_flags.json"
SEQ="$seq" FLAG_BASE="$FLAG_BASE" "${PYTHON:-python3}" - "$FLAGS_JSON" <<'PY'
import json, os, sys
seq = os.environ["SEQ"]
rec = {
  "_comment": "Render settings for the language-layer country flag font (base/fonts/flag_fonts.h, gen-lang-fonts.sh). Mirrored byte-identically in PolyKybdHost/polyhost/res/fontpack/lang_flags.json — keep both in sync (cmp). Lets the host font-pack editor rebuild a single flag: sequence-mode, source NotoColorEmoji, group = cp - seq_first.",
  "seq_first": int(os.environ["FLAG_BASE"], 16),
  "count": len([g for g in seq.split(",") if g.strip()]),
  "source": "Noto_CEmoji/NotoColorEmoji-Regular.ttf",
  "source_file": "NotoColorEmoji-Regular.ttf",
  "size": 20, "grayscale": True, "render_height": 54, "max_width": 72,
  "outline": 1, "dither": "fs", "exposure": -0.1, "composite": False,
  "sequence": seq,
}
with open(sys.argv[1], "w") as f:
    f.write(json.dumps(rec, indent=2, ensure_ascii=False) + "\n")
PY
echo "wrote $FLAGS_JSON"

# ── the ASCII label fonts moved out ──────────────────────────────────────────
# lang_label_font.h (_Tiny_) and util_font.h (_Mid_) used to be generated here.
# They are plain printable-ASCII UI text fonts with nothing language-specific
# about them, and they share their grid-fitting flags with the two status-OLED
# Base fonts, so all four now live together in fonts/gen-status-fonts.sh.
# Re-run THAT script when a UI text font changes; this one only owns the flags.
