#!/usr/bin/env python3
# Copyright 2025 thpoll83
# SPDX-License-Identifier: GPL-2.0-or-later
"""Emit a column-native (OLED page-format) companion header for a resident
range GFXfont.

The per-keycap OLED buffer is column-major (one byte = 8 VERTICAL pixels), while
the fontconvert GFXfont bitmaps are row-major (one byte = 8 HORIZONTAL pixels,
MSB-first, continuous per glyph). Drawing a legend glyph therefore normally walks
pixel-by-pixel, reading the packed glyph from XIP flash — the single biggest
sub-cost of a keycap render (loop profiler).

This tool pre-transposes every glyph of ONE font into the buffer's own
column-major layout and emits it as a `GFXfontCol` (bitmaps + per-glyph offset
table) in PROGMEM, so the firmware blits whole vertical bytes straight from
flash with no boot-time transpose and no RAM cache. The transpose is pure bit
manipulation, so it derives deterministically from the already-committed
row-major header — no fontconvert / FreeType needed, byte-reproducible anywhere.

    python3 gen_colfont.py            # regenerate base/fonts/generated/base_colfont.h
    python3 gen_colfont.py --check    # exit 1 if the committed header is stale
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import fontpack  # sibling module: reuses parse_gfx_header()

HERE = Path(__file__).resolve().parent
GEN = HERE.parent / "base" / "fonts" / "generated"

# The font(s) to mirror. Order = emit order in the header. Currently just the
# base Latin keycap face; add more resident range fonts here as they earn the
# fast path (each is a self-contained GFXfontCol, no cross-font coupling).
FONTS = [
    # (source header, GFXfont symbol)
    ("latin_fonts.h", "NotoSans_Regular_Base_14pt7b"),
]

OUT = GEN / "base_colfont.h"


def transpose_glyph(bitmaps: bytes, bmp_off: int, w: int, h: int) -> bytes:
    """Row-major, MSB-first packed glyph -> column-major page bytes.

    Mirrors the firmware blit's layout exactly: columns run x=0..w-1, each
    cb=ceil(h/8) page-bytes, page p (=yy>>3) bit (yy&7) is pixel row yy. Byte
    identical to the C transpose in kdisp_set_base_colcache_font (the runtime
    version this replaces)."""
    cb = (h + 7) // 8
    out = bytearray(w * cb)
    for yy in range(h):
        for xx in range(w):
            k = yy * w + xx                    # bit index within the glyph
            byte = bitmaps[bmp_off + (k >> 3)]
            if byte & (0x80 >> (k & 7)):
                out[xx * cb + (yy >> 3)] |= 1 << (yy & 7)
    return bytes(out)


def build_font(src_header: str, symbol: str):
    text = (GEN / src_header).read_text()
    fonts = fontpack.parse_gfx_header(text)
    if symbol not in fonts:
        raise SystemExit(f"{symbol} not found in {src_header}")
    pf = fonts[symbol]
    nglyph = pf.expected_glyph_count()
    if len(pf.glyphs) != nglyph:
        raise SystemExit(f"{symbol}: {len(pf.glyphs)} glyph records, expected {nglyph}")

    col = bytearray()
    offsets = []
    for (bmp_off, w, h, _xadv, _xoff, _yoff) in pf.glyphs:
        offsets.append(len(col))
        if w > 0 and h > 0:
            col += transpose_glyph(pf.bitmaps, bmp_off, w, h)
    return symbol, pf.first, pf.last, bytes(col), offsets


def _c_byte_array(name: str, data: bytes) -> str:
    lines = [f"const uint8_t {name}[] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i:i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def _c_u16_array(name: str, vals: list[int]) -> str:
    lines = [f"const uint16_t {name}[] PROGMEM = {{"]
    for i in range(0, len(vals), 12):
        chunk = ", ".join(str(v) for v in vals[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def render() -> str:
    out = [
        "// Auto-generated by fonts/gen_colfont.py — DO NOT EDIT.",
        "// Column-native (OLED page-format) companions for resident keycap fonts;",
        "// see GFXfontCol in base/fonts/gfxfont.h. Regenerate: python3 fonts/gen_colfont.py",
        "// Include AFTER gfxfont.h + the base font header (like the other generated",
        "// font headers, it relies on GFXfont/GFXfontCol being already defined).",
        "#pragma once",
        "",
    ]
    for src_header, symbol in FONTS:
        _sym, first, last, col, offsets = build_font(src_header, symbol)
        out.append(f"// {symbol}: {len(offsets)} glyphs "
                   f"(0x{first:X}..0x{last:X}), {len(col)} column bytes")
        out.append(f"extern const GFXfont {symbol};")
        out.append(_c_byte_array(f"{symbol}_ColBitmaps", col))
        out.append(_c_u16_array(f"{symbol}_ColOffsets", offsets))
        out.append(f"const GFXfontCol {symbol}_Col = {{")
        out.append(f"    &{symbol},")
        out.append(f"    {symbol}_ColBitmaps,")
        out.append(f"    {symbol}_ColOffsets,")
        out.append("};")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed header differs from a fresh render")
    args = ap.parse_args()

    text = render()
    if args.check:
        cur = OUT.read_text() if OUT.exists() else ""
        if cur != text:
            print(f"STALE: {OUT} differs from a fresh gen_colfont.py render", file=sys.stderr)
            return 1
        print(f"OK: {OUT} is up to date")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
