POLYMOD_PRC_PATH := modules/polykybd/polymod_prc

# The decoder is pure C (no QMK, no globals), so the suite needs no mocks: it
# decodes golden vectors generated by the HOST's encoder and compares every byte.
polymod_prc_SRC := \
	$(POLYMOD_PRC_PATH)/polymod_prc.c \
	$(POLYMOD_PRC_PATH)/tests/prc_tests.cpp

polymod_prc_INC := \
	$(POLYMOD_PRC_PATH) \
	$(POLYMOD_PRC_PATH)/tests
