#!/usr/bin/env python3
# Copyright 2025 thpoll83
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate the PolyKybd firmware-signing keypair (FW-2).

Ed25519 (RFC 8032 / SHA-512) — matches the firmware's Monocypher
``crypto_ed25519_check`` in ``base/fw_staging.c``. Run this **once**:

    python3 keyboards/polykybd/tools/gen_signing_key.py \\
        --out-privkey fw_signing_key.bin \\
        --out-pubkey  keyboards/polykybd/base/fw_pubkey.h

Then:
  * Commit the regenerated ``fw_pubkey.h`` (public key — safe to publish).
  * Keep ``fw_signing_key.bin`` SECRET. Store it as the GitHub Actions secret
    ``FW_SIGNING_KEY`` (base64, see ``--print-b64``) for release signing, and
    keep a local copy for dev signing. NEVER commit it.

Requires: ``pip install cryptography``.
"""
import argparse
import base64
import sys
from pathlib import Path

PUBKEY_TEMPLATE = '''// Copyright 2025 thpoll83
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#include <stdint.h>

// ── Firmware-image signing public key (FW-2) ────────────────────────────────
// Ed25519 public key the firmware uses to verify a signed firmware image before
// applying it (see fw_staging.c / crypto/monocypher-ed25519.h). The matching
// PRIVATE key signs releases and must NEVER live in this repo.
//
// GENERATED by keyboards/polykybd/tools/gen_signing_key.py — do not hand-edit.
// Re-run that tool to rotate the key (and re-sign all releases afterwards).

static const uint8_t FW_SIGNING_PUBKEY[32] = {
{rows}
};
'''


def _fmt_c_array(b: bytes) -> str:
    lines = []
    for i in range(0, len(b), 8):
        chunk = ", ".join(f"0x{x:02x}" for x in b[i:i + 8])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out-privkey", required=True, type=Path,
                    help="write the 32-byte raw Ed25519 seed here (KEEP SECRET)")
    ap.add_argument("--out-pubkey", required=True, type=Path,
                    help="write/overwrite the fw_pubkey.h C header here (commit it)")
    ap.add_argument("--print-b64", action="store_true",
                    help="also print the private seed base64 (for the GH secret FW_SIGNING_KEY)")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing private-key file")
    args = ap.parse_args()

    try:
        from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
        from cryptography.hazmat.primitives import serialization
    except ImportError:
        print("error: needs 'cryptography' (pip install cryptography)", file=sys.stderr)
        return 2

    if args.out_privkey.exists() and not args.force:
        print(f"refusing to overwrite existing {args.out_privkey} (use --force)", file=sys.stderr)
        return 1

    key = Ed25519PrivateKey.generate()
    seed = key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    pub = key.public_key().public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    assert len(seed) == 32 and len(pub) == 32

    args.out_privkey.write_bytes(seed)
    try:
        args.out_privkey.chmod(0o600)
    except OSError:
        pass
    args.out_pubkey.write_text(PUBKEY_TEMPLATE.replace("{rows}", _fmt_c_array(pub)))

    print(f"private seed  -> {args.out_privkey}  (KEEP SECRET, do not commit)")
    print(f"public header -> {args.out_pubkey}   (commit this)")
    if args.print_b64:
        print(f"FW_SIGNING_KEY (base64, set as a GitHub Actions secret):\n{base64.b64encode(seed).decode()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
