#!/usr/bin/env python3
# Copyright 2026 thpoll83
# SPDX-License-Identifier: GPL-2.0-or-later
"""Emit anim/menu_cascade_rows.h: each keycap panel's PHYSICAL row, per half.

    python3 tools/gen_cascade_rows.py            # from keyboards/polykybd/ ; rewrite the header
    python3 tools/gen_cascade_rows.py --check    # exit 1 if the header is stale

The menu cascade (anim/menu_cascade.c) fades a menu in row by row and keeps the bottom
row put. It used to take the row from the DISPLAY index (idx / 8), and on split72 the
two are not the same thing for the thumb cluster: the "Lang" key at matrix (4,7) and
"PgDn" at (9,0) sit on the keyboard's fourth row (keyboard.json y=3) but on the fifth
display row, so both were treated as bottom row and drawn at once while the rest of
their row cascaded (hardware).

The row here is keyboard.json's `y`, rounded: the layout the user looks at. The panel
index uses key_display_index()'s own fold, read out of split72.c by check_disp_index.py,
so the two scripts cannot disagree about which panel a key is. Keys with no OLED
(key_has_display()) are left at 0xFF.
"""
import argparse, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
KB   = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from check_disp_index import fold   # noqa: E402

BOARD, ROWS_PER_SIDE, COLS, PANELS = "split72", 5, 8, 40
NO_DISPLAY = ((3, 7), (8, 0))       # key_has_display() in split72.c
OUT = os.path.join(KB, "anim", "menu_cascade_rows.h")


def build():
    with open(os.path.join(KB, BOARD, "keyboard.json")) as f:
        d = json.load(f)
    (_, v), = d["layouts"].items()
    lo, hi = fold(BOARD)
    rows = {False: [0xFF] * PANELS, True: [0xFF] * PANELS}
    for k in v["layout"]:
        r, c = k["matrix"]
        if (r, c) in NO_DISPLAY:
            continue
        right = r >= ROWS_PER_SIDE
        cc = c
        if lo is not None and lo <= r <= hi:
            if c == 0:
                continue
            cc = c - 1
        idx = (r % ROWS_PER_SIDE) * COLS + cc
        y = int(round(k["y"]))
        if rows[right][idx] != 0xFF and rows[right][idx] != y:
            raise SystemExit("panel %d on the %s half has two keys" % (idx, "right" if right else "left"))
        rows[right][idx] = y
    return rows


def render(rows):
    out = [
        "// Copyright 2026 thpoll83",
        "// SPDX-License-Identifier: GPL-2.0-or-later",
        "// GENERATED by tools/gen_cascade_rows.py from split72/keyboard.json -- do not edit.",
        "// Each keycap panel's PHYSICAL row (keyboard.json y), indexed by display slot",
        "// (disp_row*8 + disp_col). 0xFF = no panel. See the script for why this is not",
        "// simply the display row.",
        "#pragma once",
        "#include <stdint.h>",
        "",
    ]
    for side, name in ((False, "LEFT"), (True, "RIGHT")):
        out.append("static const uint8_t CASC_ROW_%s[%d] = {" % (name, PANELS))
        for r in range(ROWS_PER_SIDE):
            cells = ", ".join("0x%02X" % x for x in rows[side][r * COLS:(r + 1) * COLS])
            out.append("    " + cells + ",")
        out.append("};")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render(build())
    if a.check:
        try:
            with open(OUT, encoding="utf-8") as f:
                cur = f.read()
        except OSError:
            cur = ""
        if cur != text:
            print("anim/menu_cascade_rows.h is stale: run tools/gen_cascade_rows.py")
            return 1
        print("anim/menu_cascade_rows.h: up to date")
        return 0
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print("wrote", os.path.relpath(OUT, KB))
    return 0


if __name__ == "__main__":
    sys.exit(main())
