// Copyright 2025 thpoll83
// SPDX-License-Identifier: GPL-2.0-or-later
#pragma once

#include <stdint.h>

// ── Firmware-image signing public key (FW-2) ────────────────────────────────
// Ed25519 public key the firmware uses to verify a signed firmware image before
// applying it (see fw_staging.c / polymod_monocypher's monocypher-ed25519.h). The matching
// PRIVATE key signs releases and must NEVER live in this repo.
//
// GENERATED by keyboards/polykybd/tools/gen_signing_key.py — do not hand-edit.
// Re-run that tool to rotate the key (and re-sign all releases afterwards).

static const uint8_t FW_SIGNING_PUBKEY[32] = {
    0x9f, 0xdc, 0x15, 0x0d, 0x2b, 0x59, 0x12, 0xad,
    0xf1, 0x13, 0xc1, 0xee, 0xb8, 0x56, 0xe8, 0x30,
    0x7b, 0x1d, 0x0f, 0x7c, 0x65, 0xfb, 0xe0, 0x33,
    0x6b, 0x8f, 0x0d, 0xc0, 0xf2, 0x5c, 0x99, 0x5a,
};
