# Copyright 2026 thpoll83
# SPDX-License-Identifier: GPL-2.0-or-later
"""Tests for modules/polykybd/polymod_prc/tools/prc_tool.py.

The tool is a port of PolyKybdHost's polyhost/util/prc_codec.py. The golden
vectors in the module's tests/prc_vectors.h were generated by the HOST's
encoder, so encoding their images here and getting the same payload bytes is
the proof that the port encodes what the firmware decodes. The table and the
vectors are read straight out of the shipped C headers, so a regenerated table
or vector file is checked too.
"""
import os
import re
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
MODULE = os.path.join(REPO, "modules", "polykybd", "polymod_prc")
sys.path.insert(0, os.path.join(MODULE, "tools"))

import prc_tool  # noqa: E402

FRAME_W, FRAME_H = 72, 40


def _bytes(text, name):
    m = re.search(r"static const uint8_t %s\[\d*\] = \{([^}]*)\}" % re.escape(name), text)
    return bytes(int(v, 16) for v in re.findall(r"0x([0-9a-f]{2})", m.group(1)))


def _vectors():
    with open(os.path.join(MODULE, "tests", "prc_vectors.h"), encoding="utf-8") as fh:
        text = fh.read()
    out = []
    for name, top, left, h, w, payload, overlay in re.findall(
            r'\{"([^"]+)", (\d+), (\d+), (\d+), (\d+), \d+, (\w+), (\w+),', text):
        out.append({
            "name": name, "top": int(top), "left": int(left), "h": int(h), "w": int(w),
            "payload": _bytes(text, payload), "overlay": _bytes(text, overlay),
        })
    return out


def _frame(overlay):
    bits = [(overlay[b >> 3] >> (7 - (b & 7))) & 1 for b in range(FRAME_W * FRAME_H)]
    return [bits[y * FRAME_W:(y + 1) * FRAME_W] for y in range(FRAME_H)]


class PrcToolTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.table = prc_tool.load_table(os.path.join(MODULE, "prc_table_v1.h"))
        cls.vectors = _vectors()

    def test_v1_table_loads_from_the_shipped_header(self):
        self.assertEqual(len(self.table), 1024)
        self.assertEqual(sum(self.table), 135654)   # the same check the C suite makes
        self.assertEqual((self.table[0], self.table[511], self.table[1023]), (252, 177, 13))

    def test_found_every_golden_vector(self):
        self.assertGreaterEqual(len(self.vectors), 7)

    def test_encoder_reproduces_the_hosts_golden_payloads(self):
        for v in self.vectors:
            with self.subTest(v["name"]):
                cropped = prc_tool.crop_to_roi(_frame(v["overlay"]))
                self.assertIsNotNone(cropped)
                top, left, roi = cropped
                self.assertEqual((top, left, len(roi), len(roi[0])), (v["top"], v["left"], v["h"], v["w"]))
                self.assertEqual(prc_tool.encode(roi, self.table).hex(), v["payload"].hex())

    def test_decoder_reproduces_the_golden_images(self):
        for v in self.vectors:
            with self.subTest(v["name"]):
                roi = prc_tool.decode(v["payload"], v["h"], v["w"], self.table)
                frame = _frame(v["overlay"])
                want = [row[v["left"]:v["left"] + v["w"]] for row in frame[v["top"]:v["top"] + v["h"]]]
                self.assertEqual(roi, want)

    def test_train_follows_the_formula(self):
        # One 3x3 block. Every pixel of it is lit, so each context the block uses
        # gets n1 > 0 and n0 = 0; a context never seen gets p0 = 128.
        block = [[1, 1, 1], [1, 1, 1], [1, 1, 1]]
        mask = [[0] * 8 for _ in range(6)]
        for y in range(3):
            for x in range(3):
                mask[2 + y][3 + x] = 1
        table = prc_tool.train([mask])
        self.assertEqual(len(table), 1024)
        seen = {}
        for c in prc_tool.contexts(block):
            seen[c] = seen.get(c, 0) + 1
        for c in range(1024):
            n1 = seen.get(c, 0)
            self.assertEqual(table[c], max(1, round(256 * 0.5 / (n1 + 1))), c)

    def test_train_ignores_order_and_empty_masks(self):
        masks = [_frame(v["overlay"]) for v in self.vectors]
        empty = [[0] * 4 for _ in range(4)]
        self.assertEqual(prc_tool.train(masks), prc_tool.train(list(reversed(masks)) + [empty]))

    def test_a_trained_table_round_trips_through_the_header(self):
        table = prc_tool.train([_frame(v["overlay"]) for v in self.vectors])
        with tempfile.TemporaryDirectory() as tmp:
            path = os.path.join(tmp, "prc_table_v9.h")
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(prc_tool.header(table, 9, "test images"))
            self.assertEqual(prc_tool.load_table(path), table)
        for v in self.vectors:
            roi = prc_tool.crop_to_roi(_frame(v["overlay"]))[2]
            payload = prc_tool.encode(roi, table)
            self.assertEqual(prc_tool.decode(payload, len(roi), len(roi[0]), table), roi)

    def test_bad_tables_are_refused(self):
        with self.assertRaises(ValueError):
            prc_tool.encode([[1]], bytes(1023))
        with self.assertRaises(ValueError):
            prc_tool.encode([[1]], bytes(1024))   # a 0 probability


if __name__ == "__main__":
    unittest.main()
