#!/usr/bin/env bash
# Generate the two standalone font headers used by the language-selection layer
# (_LL):
#
#   base/fonts/flag_fonts.h        country flags (NotoColorEmoji, 28 px)
#   base/fonts/lang_label_font.h   tiny language-code label font (NotoSans 6 px)
#
# Both are used via dedicated single-font arrays in the keymap (see
# render_lang_flag_key in split72/keymaps/default/keymap.c); they are NOT part of
# fonts.yaml / ALL_FONTS — like the status-OLED fonts they are standalone
# committed headers.  Re-run this only when the language list or the look changes.
#
# Each flag is a two-codepoint regional-indicator pair (e.g. US = U+1F1FA U+1F1F8)
# shaped by HarfBuzz into a single glyph, then mapped to a Private-Use codepoint
# (FLAG_CP_BASE + LANG_* enum index) via fontconvert's -F option, so the firmware
# can address it as one char.
#
# Requirements:
#   * NotoColorEmoji   at fonts/Noto_CEmoji/NotoColorEmoji-Regular.ttf
#   * NotoSans         at fonts/noto-sans/NotoSans-Regular.ttf
#       (both fetched by fonts/dl-fonts.sh)
#   * a fontconvert with -F (sequence base codepoint) support — see AdafruitGFX.
#     For byte-reproducible output use the PINNED build (FreeType 2.13.3 /
#     HarfBuzz 2.6.7); the distro fast-path build differs by ~1px on a few glyphs.
#     Override the binary with $FONTCONVERT.
#
# IMPORTANT: the country list below MUST stay in the same order as
# enum lang_layer in lang/lang_lut.h (LANG_ENUS = 0, LANG_DEDE = 1, ...), so that
# flag codepoint == FLAG_CP_BASE + LANG_* and local_state->lang indexes it.
set -euo pipefail
cd "$(dirname "$0")/.."                       # -> the keyboard directory

FONTCONVERT="${FONTCONVERT:-fontconvert}"
EMOJI="fonts/Noto_CEmoji/NotoColorEmoji-Regular.ttf"
SANS="fonts/noto-sans/NotoSans-Regular.ttf"
FLAG_OUT="base/fonts/flag_fonts.h"
LABEL_OUT="base/fonts/lang_label_font.h"
FLAG_BASE="0xE000"                            # keep in sync with FLAG_CP_BASE in the keymap

# ISO 3166-1 alpha-2 country code per language, in enum lang_layer order.
# DERIVED from the single source of truth, lang/lang_lut.xlsx: the "YY" part of
# each "xx-YY" language name in key_lut row 1, in column (= enum) order. Never
# hand-edit this list - add the language to the spreadsheet and re-run.
# Capture the extractor's stdout AND exit status first, so a partial dump
# followed by a Python error fails the whole script instead of silently
# truncating COUNTRIES (which would shift every LANG_* flag off its enum index).
countries="$("${PYTHON:-python3}" - lang/lang_lut.xlsx <<'PY'
import sys
from openpyxl import load_workbook
sheet = load_workbook(sys.argv[1], read_only=True, data_only=True)["key_lut"]
i = 0
while True:
    name = sheet.cell(row=1, column=2 + i * 4).value
    if not name:
        break
    print(name.split("-")[1].upper())   # es-MX -> MX, th-TH -> TH, ...
    i += 1
PY
)" || {
    echo "ERROR: could not read the language list from lang/lang_lut.xlsx" \
         "(need ${PYTHON:-python3} with openpyxl)." >&2
    exit 1
}
if [ -z "$countries" ]; then
    echo "ERROR: empty language list from lang/lang_lut.xlsx" \
         "(need ${PYTHON:-python3} with openpyxl)." >&2
    exit 1
fi
mapfile -t COUNTRIES <<<"$countries"

# Regional-indicator codepoint (hex) for an ASCII A-Z letter.
ri() { printf '%X' "$(( 0x1F1E6 + $(printf '%d' "'$1") - 65 ))"; }

seq=""
for cc in "${COUNTRIES[@]}"; do
    pair="$(ri "${cc:0:1}") $(ri "${cc:1:1}")"
    seq="${seq:+$seq, }$pair"
done

# ── flags ────────────────────────────────────────────────────────────────────
{
    echo "// Copyright 2025 thpoll83"
    echo "// SPDX-License-Identifier: GPL-2.0-or-later"
    echo "#pragma once"
    echo "// GENERATED by fonts/gen-lang-fonts.sh — do not hand-edit."
    echo "// Language-layer country flags: NotoColorEmoji, rendered at 54 px (taller"
    echo "// than the 40 px keycap) so the keymap can vertically centre + clip them and"
    echo "// have the flag content fill the height.  1 px inner border, Floyd-Steinberg"
    echo "// dither.  first = ${FLAG_BASE} + LANG_* enum index"
    echo "// (order = enum lang_layer in lang/lang_lut.h)."
    "$FONTCONVERT" -f"$EMOJI" -s20 -g -r54 -W72 -O1 -Dfs -e-0.10 \
                   -F"$FLAG_BASE" -v_LangFlags_ -S "$seq"
} > "$FLAG_OUT"
echo "wrote $FLAG_OUT ($(grep -c '// seq\[' "$FLAG_OUT") flags)"

# ── tiny label font (printable ASCII) ────────────────────────────────────────
{
    echo "// Copyright 2025 thpoll83"
    echo "// SPDX-License-Identifier: GPL-2.0-or-later"
    echo "#pragma once"
    echo "// GENERATED by fonts/gen-lang-fonts.sh — do not hand-edit."
    echo "// Tiny label font for the language codes under each flag (NotoSans Medium 6 px)."
    "$FONTCONVERT" -f"$SANS" -s6 -w500 -v_Tiny_ 0x20 0x7e
} > "$LABEL_OUT"
echo "wrote $LABEL_OUT"

# ── mid utility-label font (printable ASCII) ─────────────────────────────────
# A 10 px size between the 6 px _Tiny_ label and the 14 px _Base_ keycap font,
# for misc utility-key text (e.g. the no-pack language-code fallback). Standalone
# header (NOT in fonts.yaml/ALL_FONTS) used via a dedicated single-font array, so
# it never competes with _Base_ over the ASCII range.
UTIL_OUT="base/fonts/util_font.h"
{
    echo "// Copyright 2025 thpoll83"
    echo "// SPDX-License-Identifier: GPL-2.0-or-later"
    echo "#pragma once"
    echo "// GENERATED by fonts/gen-lang-fonts.sh — do not hand-edit."
    echo "// Mid utility-label font (NotoSans Medium 10 px) — between the 6 px _Tiny_"
    echo "// label and the 14 px _Base_ keycap font, for misc utility-key text."
    "$FONTCONVERT" -f"$SANS" -s10 -w500 -v_Mid_ 0x20 0x7e
} > "$UTIL_OUT"
echo "wrote $UTIL_OUT"
